# This is the configuration file for all the knockback profiles, in here you can
# easily setup profiles, change knockback values, and change default knockback
# or create knockback profiles manually. Be careful while editing these manually
# though, because this configuration can easily break!
# 

DEFAULT-KNOCKBACK: default
PROFILES:
  DEFAULT:
    TYPE: EASY
    # Horizontal Multiplier
    HORIZONTAL: 0.69
    # Vertical Value
    VERTICAL: 0.69
    # Add a certain value to horizontal/vertical before actual calculations
    EXTRA-HORIZONTAL: 0.0544
    EXTRA-VERTICAL: 0.0
    # Friction Value (Knockback is divided by this)
    FRICTION: 1.1
    # Y-Axis Limit for a player's velocity
    Y-LIMIT: 0.3555
    DAMAGE-TICKS:
      # Override vanilla damage ticks with carbon's
      OVERRIDE: true
      # The delay between a player's ability to damage an entity
      VALUE: 20
      # Disables damage ticks for rods and arrows
      BETTER-DETECTION: false
    # Should the vertical velocity be set to 0 after reaching limit?
    DYNAMIC-LIMIT: false
    # Should we limit horizontal movement?
    LIMIT-HORIZONTAL: false
    # X/Z-Axis Limit for a player's velocity
    H-LIMIT: 0.45
    PROJECTILES:
      Y-LIMIT:
        # Should we limit projectile's vertical kb?
        ENABLED: true
        # Vertical limit value of projectiles
        VALUE: 0.4000000059604645
      ARROW:
        # Override vanilla arrow knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by an Arrow
        HORIZONTAL: 0.4
        # Vertical knockback dealt by an Arrow
        VERTICAL: 0.4
        # Toggle whether an arrow moves you in a straight line
        STRAIGHT-BOOST: false
      FISH-ROD:
        # Override vanilla rod knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Fish-Rod
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Fish-Rod
        VERTICAL: 0.4
        # Multiplies the amount given with the rod's vector magnitude (Faster/Smoother Rodding)
        SPEED: 2.2
      PEARL:
        # Override vanilla pearl knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Pearl
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Pearl
        VERTICAL: 0.4
      EXPLODE:
        # Override vanilla explosion knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Explosion
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Explosion
        VERTICAL: 0.4
        # Toggle whether an explosion moves you in a straight line
        STRAIGHT-BOOST: false
      SNOW-BALL:
        # Override vanilla snowball knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Snowball
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Snowball
        VERTICAL: 0.4
      EGG:
        # Override vanilla egg knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Egg
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Egg
        VERTICAL: 0.4
      POTION:
        # Override settings.yml potion settings with this
        OVERRIDE: false
        # Splash potion's falling speed
        SPEED: 0.593
        # Splash potion's negative y-velocity
        GRAVITY: 0.05
        # Splash potion's vertical offset
        VERTICAL-OFFSET: -20.0
        # Splash potion's horizontal offset
        HORIZONTAL-OFFSET: 0.0
    # Should we use 1.7 Knockback?
    ONE-POINT-SEVEN: false
  DETAILED:
    TYPE: DETAILED
    # Horizontal Multiplier
    HORIZONTAL: 0.57
    # Vertical Value
    VERTICAL: 0.36
    # Add a certain value to horizontal before actual calculations
    INHERIT-H-ENABLED: false
    INHERIT-H-VALUE: 1.4
    # Add a certain value to vertical before actual calculations
    INHERIT-V-ENABLED: false
    INHERIT-V-VALUE: 1.0
    # Friction values, actual knockback is divided by this
    FRICTION-H: 0.0
    FRICTION-V: 0.0
    # When player is hit but on ground, this value is multiplied with initial kb
    GROUND-H: 1.0
    GROUND-V: 1.0
    # When player is hit but attacker is spriting, this value is multiplied with initial kb
    SPRINT-H: 1.345
    SPRINT-V: 1.0
    # Should we dynamically limit player's vertical axis?
    Y-LIMIT: true
    # Dynamic vertical axis limit value
    Y-LIMIT-VALUE: 1.2
    # Should the attacker have their sprint reset upon attacking
    STOP-SPRINT: true
    # This value is multiplied in horizontal axis after calculations and sprint reset
    SLOWDOWN: 0.2
    COMBO:
      # Toggle combo mode
      ENABLED: false
      # This is used to track when to move player back down from y axis
      TICKS: 10
      # Horizontal velocity of a player in combo mode
      VELOCITY: -0.05
      # Vertical velocity of a player in combo mode
      HEIGHT: 2.5
    DAMAGE-TICKS:
      # Override vanilla damage ticks with carbon's
      OVERRIDE: true
      # The delay between a player's ability to damage an entity
      VALUE: 19
      # Disables damage ticks for rods and arrows
      BETTER-DETECTION: true
    PROJECTILES:
      Y-LIMIT:
        # Should we limit projectile's vertical kb?
        ENABLED: true
        # Vertical limit value of projectiles
        VALUE: 0.4000000059604645
      ARROW:
        # Override vanilla arrow knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by an Arrow
        HORIZONTAL: 0.4
        # Vertical knockback dealt by an Arrow
        VERTICAL: 0.4
        # Toggle whether an arrow moves you in a straight line
        STRAIGHT-BOOST: true
      FISH-ROD:
        # Override vanilla rod knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Fish-Rod
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Fish-Rod
        VERTICAL: 0.4
        # Multiplies the amount given with the rod's vector magnitude (Faster/Smoother Rodding)
        SPEED: 2.2
      PEARL:
        # Override vanilla pearl knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Pearl
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Pearl
        VERTICAL: 0.4
      EXPLODE:
        # Override vanilla explosion knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Explosion
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Explosion
        VERTICAL: 0.4
        # Toggle whether an explosion moves you in a straight line
        STRAIGHT-BOOST: true
      SNOW-BALL:
        # Override vanilla snowball knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Snowball
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Snowball
        VERTICAL: 0.4
      EGG:
        # Override vanilla egg knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Egg
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Egg
        VERTICAL: 0.4
      POTION:
        # Override settings.yml potion settings with this
        OVERRIDE: false
        # Splash potion's falling speed
        SPEED: 0.593
        # Splash potion's negative y-velocity
        GRAVITY: 0.05
        # Splash potion's vertical offset
        VERTICAL-OFFSET: -20.0
  TNT:
    TYPE: DETAILED
    # Horizontal Multiplier
    HORIZONTAL: 0.44452682
    # Vertical Value
    VERTICAL: 0.3555
    # Add a certain value to horizontal before actual calculations
    INHERIT-H-ENABLED: true
    INHERIT-H-VALUE: 1.4
    # Add a certain value to vertical before actual calculations
    INHERIT-V-ENABLED: false
    INHERIT-V-VALUE: 1.0
    # Friction values, actual knockback is divided by this
    FRICTION-H: 2.0
    FRICTION-V: 2.0
    # When player is hit but on ground, this value is multiplied with initial kb
    GROUND-H: 1.2
    GROUND-V: 1.0
    # When player is hit but attacker is spriting, this value is multiplied with initial kb
    SPRINT-H: 1.2
    SPRINT-V: 1.0
    # Should we dynamically limit player's vertical axis?
    Y-LIMIT: true
    # Dynamic vertical axis limit value
    Y-LIMIT-VALUE: 1.2
    # Should the attacker have their sprint reset upon attacking
    STOP-SPRINT: true
    # This value is multiplied in horizontal axis after calculations and sprint reset
    SLOWDOWN: 0.2
    COMBO:
      # Toggle combo mode
      ENABLED: false
      # This is used to track when to move player back down from y axis
      TICKS: 10
      # Horizontal velocity of a player in combo mode
      VELOCITY: -0.05
      # Vertical velocity of a player in combo mode
      HEIGHT: 2.5
    DAMAGE-TICKS:
      # Override vanilla damage ticks with carbon's
      OVERRIDE: true
      # The delay between a player's ability to damage an entity
      VALUE: 20
      # Disables damage ticks for rods and arrows
      BETTER-DETECTION: false
    PROJECTILES:
      Y-LIMIT:
        # Should we limit projectile's vertical kb?
        ENABLED: true
        # Vertical limit value of projectiles
        VALUE: 0.4000000059604645
      ARROW:
        # Override vanilla arrow knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by an Arrow
        HORIZONTAL: 0.4
        # Vertical knockback dealt by an Arrow
        VERTICAL: 0.4
        # Toggle whether an arrow moves you in a straight line
        STRAIGHT-BOOST: false
      FISH-ROD:
        # Override vanilla rod knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Fish-Rod
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Fish-Rod
        VERTICAL: 0.4
        # Multiplies the amount given with the rod's vector magnitude (Faster/Smoother Rodding)
        SPEED: 2.2
      PEARL:
        # Override vanilla pearl knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Pearl
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Pearl
        VERTICAL: 0.4
      EXPLODE:
        # Override vanilla explosion knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Explosion
        HORIZONTAL: 0.9
        # Vertical knockback dealt by a Explosion
        VERTICAL: 1.0
        # Toggle whether an explosion moves you in a straight line
        STRAIGHT-BOOST: true
      SNOW-BALL:
        # Override vanilla snowball knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Snowball
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Snowball
        VERTICAL: 0.4
      EGG:
        # Override vanilla egg knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Egg
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Egg
        VERTICAL: 0.4
      POTION:
        # Override settings.yml potion settings with this
        OVERRIDE: false
        # Splash potion's falling speed
        SPEED: 0.593
        # Splash potion's negative y-velocity
        GRAVITY: 0.05
        # Splash potion's vertical offset
        VERTICAL-OFFSET: -20.0
  COMBO:
    TYPE: DETAILED
    # Horizontal Multiplier
    HORIZONTAL: 0.3
    # Vertical Value
    VERTICAL: 0.3
    # Add a certain value to horizontal before actual calculations
    INHERIT-H-ENABLED: true
    INHERIT-H-VALUE: 1.4
    # Add a certain value to vertical before actual calculations
    INHERIT-V-ENABLED: false
    INHERIT-V-VALUE: 1.0
    # Friction values, actual knockback is divided by this
    FRICTION-H: 2.0
    FRICTION-V: 2.0
    # When player is hit but on ground, this value is multiplied with initial kb
    GROUND-H: 1.2
    GROUND-V: 1.0
    # When player is hit but attacker is spriting, this value is multiplied with initial kb
    SPRINT-H: 1.2
    SPRINT-V: 1.0
    # Should we dynamically limit player's vertical axis?
    Y-LIMIT: true
    # Dynamic vertical axis limit value
    Y-LIMIT-VALUE: 1.2
    # Should the attacker have their sprint reset upon attacking
    STOP-SPRINT: true
    # This value is multiplied in horizontal axis after calculations and sprint reset
    SLOWDOWN: 0.2
    COMBO:
      # Toggle combo mode
      ENABLED: false
      # This is used to track when to move player back down from y axis
      TICKS: 10
      # Horizontal velocity of a player in combo mode
      VELOCITY: -0.05
      # Vertical velocity of a player in combo mode
      HEIGHT: 2.5
    DAMAGE-TICKS:
      # Override vanilla damage ticks with carbon's
      OVERRIDE: true
      # The delay between a player's ability to damage an entity
      VALUE: 5
      # Disables damage ticks for rods and arrows
      BETTER-DETECTION: true
    PROJECTILES:
      Y-LIMIT:
        # Should we limit projectile's vertical kb?
        ENABLED: true
        # Vertical limit value of projectiles
        VALUE: 0.4000000059604645
      ARROW:
        # Override vanilla arrow knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by an Arrow
        HORIZONTAL: 0.4
        # Vertical knockback dealt by an Arrow
        VERTICAL: 0.4
        # Toggle whether an arrow moves you in a straight line
        STRAIGHT-BOOST: false
      FISH-ROD:
        # Override vanilla rod knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Fish-Rod
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Fish-Rod
        VERTICAL: 0.4
        # Multiplies the amount given with the rod's vector magnitude (Faster/Smoother Rodding)
        SPEED: 2.2
      PEARL:
        # Override vanilla pearl knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Pearl
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Pearl
        VERTICAL: 0.4
      EXPLODE:
        # Override vanilla explosion knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Explosion
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Explosion
        VERTICAL: 0.4
        # Toggle whether an explosion moves you in a straight line
        STRAIGHT-BOOST: false
      SNOW-BALL:
        # Override vanilla snowball knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Snowball
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Snowball
        VERTICAL: 0.4
      EGG:
        # Override vanilla egg knockback with carbon's
        OVERRIDE: true
        # Horizontal knockback dealt by a Egg
        HORIZONTAL: 0.4
        # Vertical knockback dealt by a Egg
        VERTICAL: 0.4
      POTION:
        # Override settings.yml potion settings with this
        OVERRIDE: false
        # Splash potion's falling speed
        SPEED: 0.593
        # Splash potion's negative y-velocity
        GRAVITY: 0.05
        # Splash potion's vertical offset
        VERTICAL-OFFSET: -20.0
